config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    member do 
      put :vote
    end
  end
  
  root 'candidates#index'
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    validates :name, presence: true
    validates :age, numericality: { greater_than_or_equal_to: 40}
    has_many :votelog, dependent: :destroy
end

app/models/votelog.rb
class Votelog < ApplicationRecord
  belongs_to :candidate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
    before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote]

    def index
      @candidates = Candidate.all.order(vote: :desc).page(params[:pages]).per(5)
    end

    def show
      
    end

    def new
      @candidate = Candidate.new
    end
    
    def edit
      
    end

    def vote
      
      # @candidate.update(vote: @candidate.vote + 1)
      Votelog.create(candidate_id: @candidate.id, ip_address: request.remote_ip)
      redirect_to root_path, notice: '投票成功'
      
    end

    def create
      @candidate = Candidate.new(candidate_params)
      if @candidate.save
        redirect_to root_path, notice: "新增候選人成功!"
      else 
        render :new
        # render html: "fail"
      end
      # render html: params
    end

    def update
      if @candidate.update(candidate_params)
        #成功
        redirect_to root_path, notice: "更新成功"
      else
        #失敗
        render :edit
      end
    end

    def destroy
      @candidate.destroy if @candidate
      redirect_to candidates_path, notice: "資料刪除成功"
    end


    def find_candidate
      @candidate = Candidate.find_by(id: params[:id])
    end

    def candidate_params
      params.require(:candidate).permit(:name,:age,:party,:policy,:degree)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<% if @candidate.errors.any? %>
  <ul>
    <% @candidate.errors.full_messages.each do |message|%>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= simple_form_for(@candidate) do |form| %>
<div class = "box">
<%= form.input :name, label: "姓名" %>
<%= form.input :degree, label: "學歷" %>
<%= form.input :party, label: "黨派" %>
<%= form.input :age, label: "年紀" %>
<%= form.input :policy, label: "政見" %>
<%= form.submit  class:'btn btn-success' %>
</div>

<% end %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<%= render 'form', candidate: @candidate%>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>
<%= paginate @candidates %>
<ul>
<% @candidates.each do |candidate| %>
<%= link_to "投給這位？", vote_candidate_path(candidate.id), class: 'btn btn-xs btn-warning', method: 'put', data: { confirm: "確定要投給他嗎？"}%>
    <li>
    <%= candidate.vote%>票
    <%= link_to candidate.name, candidate_path(candidate.id) %>
    <%= link_to "編輯", edit_candidate_path(candidate.id), class: 'btn bg-xs btn-success'%>
    <%= link_to "刪除", candidate_path(candidate.id), method: 'delete', data: { confirm: '確定要刪除嗎？'},class: 'btn bg-xs btn-danger' %>
    </li>
<% end %>
</ul>
<%= link_to '新增候選人', new_candidate_path, class: 'btn btn-danger btn-lg'%>

app/views/candidates/new.html.erb
<h1>新增候選人</h1> 
<%# <%= link_to '回列表頁', candidates_path, class: 'btn btn-lg btn-danger'%> 
<%# <form action="/candidates" method="post">
<input type="text" name="username">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>
<%# <input type="submit">
</form> %>

<%= render 'form', candidate: @candidate %>

app/views/candidates/show.html.erb
<% if @candidate%>
<h1> <%= @candidate.name%></h1>

<ul>
    <li>得票數: <%= @candidate.vote%></li>
    <li>年紀: <%= @candidate.age%></li>
    <li>學歷: <%= @candidate.degree%></li>
    <li>黨派: <%= @candidate.party%></li>
    <li>政見: <%= @candidate.policy%></li>
</ul>
<% else%>
    <h1>查無此人</h1>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ivoting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/frontend/navbar' %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>